name: dreamtoflutter
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  starlight_search_bar: 
    git:
      url: https://github.com/YeMyoAung/starlight_search_bar.git
  starlight_type_ahead: 
    git:
      url: https://github.com/YeMyoAung/StarlightTypeAhead.git
  starlight_utils:
  http:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
